base_url = "https://nan-mu.asia"
compile_sass = true
title = "A blog by Ye Zhengnan"
description = "真希望我能写好多好博客"
generate_feeds = true
theme = "radion"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
build_search_index = true
default_language = "en"

[languages.zh]

[languages.jp]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
insert_anchor_links = "heading"
highlight_themes_css = [
  { theme = "one-dark", filename = "syntax/syntax-theme-dark.css" },
  { theme = "gruvbox-dark", filename = "syntax/syntax-theme-light.css" },
]

[search]
index_format = "elasticlunr_json"

[extra]
author = "Ye Zhengnan"
github = "https://github.com/nan-mu"
# fediverse.creator = "@username@my.instance.example.com"
# fediverse.rel_me = "https://my.instance.example.com/@username"
# mastodon = "https://my.instance.example.com/@username"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
radion_title = "Ye Zhengnan's Blog"
codeblock = true
latex = true
enable_search = true
theme = "toggle" # options: {light, dark, auto, toggle}
favicon = true
comments = true
giscus_repo = "nan-mu/nan-mu.github.io"
giscus_repo_id = "R_kgDOMkLDRQ"
giscus_data_category_id = "DIC_kwDOMkLDRc4CtsQb"
revision_history = true
blog_github_repo_url = "https://github.com/nan-mu/nan-mu.github.io"
lang_aliases = { en = "English", zh = "中文", jp = "日本語", ko = "한국어" }